import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nextjs Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Nextjs Todo app</h1>
        <form>
          <input type="text" />
          <button>Submit</button>
        </form>
      </div>
    </div>
  );
}
